import { writeFile } from 'node:fs/promises'

const SOURCES = [
  {
    name: 'HubSpot blocked domains',
    url: 'https://f.hubspotusercontent40.net/hubfs/2832391/Marketing/Lead-Capture/free-domains-2.csv'
  },
  {
    name: 'Castle disposable email domains',
    url: 'https://raw.githubusercontent.com/castle/disposable-email-domains/master/disposable-email-domains.txt'
  },
  {
    name: 'Disposable email domains blocklist',
    url: 'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf'
  }
]

/** Additional domains not present in the URL */
const DOMAINS = [
  '2iij.net',
  'adsl.no',
  'aol.co.uk',
  'aol.de',
  'aol.fr',
  'asahi-net.or.jp',
  'atlas.cz',
  'au.com',
  'auone-net.jp',
  'azet.sk',
  'bbiq.jp',
  'bbnett.no',
  'bbtec.net',
  'biglobe.ne.jp',
  'biz.ezweb.ne.jp',
  'bluezone.no',
  'broadpark.no',
  'chello.no',
  'chol.com',
  'chollian.net',
  'commufa.jp',
  'daum.net',
  'dion.ne.jp',
  'disney.ne.jp',
  'docomo.ne.jp',
  'dreamwiz.com',
  'dti.ne.jp',
  'e-mail.de',
  'ebnett.no',
  'emnet.ne.jp',
  'emobile.ne.jp',
  'eonet.ne.jp',
  'epost.no',
  'euromail.hu',
  'ezweb.ne.jp',
  'freechal.com',
  'freemail.ne.jp',
  'frisurf.no',
  'getmail.no',
  'gmx-ist-cool.de',
  'gmx-topmail.de',
  'gmx.ca',
  'gmx.co.uk',
  'gmx.es',
  'gmx.fr',
  'gmx.hk',
  'gmx.ie',
  'gmx.pt',
  'gmx.sg',
  'gmx.tw',
  'gmx.us',
  'hanafos.com',
  'hananet.net',
  'hanmail2.net',
  'hanmir.com',
  'haugnett.no',
  'hi-ho.ne.jp',
  'hitel.net',
  'hotmail.be',
  'hotmail.co.in',
  'hotmail.co.kr',
  'hotmail.co.th',
  'hotmail.cz',
  'hotmail.dk',
  'hotmail.gr',
  'hotmail.hu',
  'hotmail.jp',
  'hotmail.my',
  'hotmail.no',
  'hotmail.ph',
  'hotmail.sg',
  'i.softbank.jp',
  'iij4u.or.jp',
  'inbox.lt',
  'inbox.lv',
  'indamail.hu',
  'infoseek.co.jp',
  'infoseek.jp',
  'infoweb.ne.jp',
  'interia.eu',
  'jcom.home.ne.jp',
  'jcom.zaq.ne.jp',
  'jubii.dk',
  'jubiichat.dk',
  'jubiiconnect.dk',
  'jubiigames.dk',
  'jubiipost.dk',
  'jubiipostadresse.dk',
  'kakao.com',
  'kcn.ne.jp',
  'kornet.net',
  'lajt.hu',
  'live.co.kr',
  'live.hk',
  'livedoor.com',
  'losmail.no',
  'lyse.net',
  'mail.bbexcite.jp',
  'mail.byte.it',
  'mail.ch',
  'mail.dk',
  'mail.fr',
  'mail.goo.ne.jp',
  'mail.lv',
  'mail.sony.jp',
  'mail.vu',
  'megaegg.ne.jp',
  'mesh.ad.jp',
  'meta.ua',
  'mimer.no',
  'mineo.jp',
  'mopera.net',
  'msn.co.uk',
  'nana10.co.il',
  'nate.com',
  'net.ua',
  'netcom.no',
  'netsgo.com',
  'neuf.fr',
  'nifty.com',
  'nifty.ne.jp',
  'noos.fr',
  'nownuri.net',
  'ntebb.no',
  'o2.pl',
  'ocn.ne.jp',
  'odn.ad.jp',
  'odn.ne.jp',
  'online-home.de',
  'online.de',
  'online.no',
  'onlinehome.de',
  'panda.tnc.ne.jp',
  'paran.com',
  'pdx.ne.jp',
  'pikara.ne.jp',
  'plala.or.jp',
  'pm.me',
  'poczta.onet.eu',
  'posteo.af',
  'posteo.co.uk',
  'posteo.cr',
  'posteo.cz',
  'posteo.ee',
  'posteo.eu',
  'posteo.fi',
  'posteo.gr',
  'posteo.hn',
  'posteo.hr',
  'posteo.hu',
  'posteo.ie',
  'posteo.in',
  'posteo.is',
  'posteo.jp',
  'posteo.la',
  'posteo.li',
  'posteo.lt',
  'posteo.lu',
  'posteo.me',
  'posteo.mx',
  'posteo.my',
  'posteo.nl',
  'posteo.nz',
  'posteo.org',
  'posteo.pe',
  'posteo.pl',
  'posteo.pm',
  'posteo.pt',
  'posteo.ro',
  'posteo.ru',
  'posteo.se',
  'posteo.sg',
  'posteo.si',
  'posteo.tn',
  'posteo.uk',
  'proton.me',
  'protonmail.ch',
  'qip.ru',
  'rakumail.jp',
  'rakuten.jp',
  'sakura.ne.jp',
  'sensewave.com',
  'sfr.fr',
  'sky.tkc.ne.jp',
  'sky.tkk.ne.jp',
  'sky.tu-ka.ne.jp',
  'so-net.ne.jp',
  'softbank.ne.jp',
  'spaaqs.ne.jp',
  'spambox.xyz',
  'start.no',
  't-com.ne.jp',
  't-online.hu',
  'tele2.no',
  'tempmail.net',
  'thexyz.ca',
  'thexyz.fr',
  'thexyz.in',
  'thexyz.mobi',
  'thexyz.net',
  'thexyz.org',
  'thrunet.com',
  'tiki.ne.jp',
  'tiscali.no',
  'tistory.com',
  'tlen.pl',
  'tokai.or.jp',
  'tuta.io',
  'tutanota.de',
  'ucom.ne.jp',
  'ukrpost.net',
  'unitel.co.kr',
  'uqmobile.jp',
  'vipmail.hu',
  'vodafone.ne.jp',
  'voila.fr',
  'walla.co.il',
  'wcm.ne.jp',
  'willcom.com',
  'yandex.by',
  'yandex.kz',
  'ybb.ne.jp',
  'ymail.ne.jp',
  'ymobile.ne.jp',
  'ymobile1.ne.jp',
  'zahav.net.il',
  'zaq.ne.jp'
]

const trim = text => text.replace(/^\s+|\s+$/g, '')

const sanitize = text =>
  text
    .split(/[,\n]/g)
    .map(trim)
    .filter(domain => domain && !domain.startsWith('#'))

async function fetchSource (source) {
  const res = await fetch(source.url)

  if (!res.ok) {
    throw new Error(`Unable to fetch ${source.name} (${res.status})`)
  }

  const text = await res.text()

  if (text.startsWith('<!DOCTYPE html') || text.includes('<html')) {
    throw new Error(`Received HTML instead of domain list for ${source.name}`)
  }

  return sanitize(text)
}

async function main () {
  const sourceDomains = await Promise.all(SOURCES.map(fetchSource))
  const domains = new Set(sourceDomains.flat())
  for (const domain of DOMAINS) domains.add(domain)
  const sorted = Array.from(domains).sort()
  await writeFile('domains.json', JSON.stringify(sorted, null, 2))
}

main().catch(error => console.error(error) || process.exit(1))
