#!/usr/bin/env node

'use strict';

const jsonFuture = require('json-future');
const getStdin = require('get-stdin');
const { concat } = require('lodash');
const cheerio = require('cheerio');

const REGEX_SEPARATOR = new RegExp('<br>', 'g');

try {
  (async () => {
    const body = await getStdin();

    const $ = cheerio.load(body);
    let result = [];

    $('span > p').each(function(i, el) {
      if (i !== 0) {
        const domains = $(this)
          .html()
          .replace(REGEX_SEPARATOR, ' ')
          .split(' ');

        result = concat(result, domains);
      }
    });

    await jsonFuture.saveAsync('domains.json', result);
  })();
} catch (err) {
  console.error('Unable to fetch the domains list');
}
