name: cron

on:
  schedule:
    # Cron job every day at 12:00
    # https://crontab.guru/#0_12_*_*_*
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Cron
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}g
          npm run postinstall
          git add domains.json
          git diff-index --quiet HEAD || git commit -m 'build(update): emails' --no-verify
          git push origin ${{ github.head_ref }} || true
          curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/5da57132-d653-45c9-820b-87d7e03115a3
