name: cron

on:
  schedule:
    # Cron job every Monday at 12:00
    # https://crontab.guru/every-monday
    - cron:  '0 0 * * MON'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install
        run: npm install --no-package-lock
      - name: Cron
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          npm run cronjob
